apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mercurysx/frontend:{{BUILD_NUMBER}}
          resources:
            limits:
              memory: '500Mi'
              cpu: '0.2'
      nodeSelector:
        role: master
